# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-02-05 11:56
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=30)),
                ('nric', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Contact phone number', max_length=128, region=None)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.CharField(blank=True, max_length=30, null=True)),
                ('q2', models.CharField(blank=True, max_length=30, null=True)),
                ('q3', models.CharField(blank=True, max_length=30, null=True)),
                ('q4', models.CharField(blank=True, max_length=30, null=True)),
                ('q5', models.CharField(blank=True, max_length=30, null=True)),
                ('q6', models.CharField(blank=True, max_length=30, null=True)),
                ('times', models.CharField(blank=True, max_length=30, null=True)),
                ('reason_q2', models.CharField(blank=True, max_length=30, null=True)),
                ('reason_q3', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
