# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-03-20 16:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='incidenttime',
            field=models.TimeField(default=datetime.datetime(2020, 3, 21, 1, 41, 2, 172855)),
        ),
    ]
